#!/bin/bash

blah=(
one two three four four four five one one two one two three four one two three
four four four five one one two one two three four one two three four four four
five one one two one two three four one two three four one two three four one
two three four one two three four four four five one one two one two three four
one two three four four four five one one two one two three four one two three
four one five six seven eight eight eight eight eight eight nine ten
)

declare -A histogram

# Create histogram - note type is a string
for b in ${blah[*]}; do
	histogram[$b]+=-
done

# Dump histogram
echo histogram of strings
for key in ${!histogram[*]}; do
	echo -e $key\\t${histogram[$key]}\|
done

# Looks cool as it is!

# four	---------------|
# one	---------------|
# five	---|
# two	------------|
# three	---------|

# But how about a histogram of integers?
echo
echo histogram of integers
declare -A histogram_int
declare -i init=1

# Create histogram - note type is a string
for b in ${blah[*]}; do

	# If the key doesn't exist initialise it with an integer
	if [[ ! ${histogram_int[$b]} ]]; then
		histogram_int[$b]=$init
	else
		# Otherwise increment the existing value
		histogram_int[$b]=$(( histogram_int[$b] + 1 ))
	fi
done

# Dump histogram
for key in ${!histogram_int[*]}; do
	echo -e $key\\t${histogram_int[$key]}
done
