#!/bin/bash

# Get list of scripts
mapfile scripts < <(ls *)

# Calculate an index for the day
i=$(( ($(date +%d) * $(date +%m) * $(date +%y)) % ${#scripts[*]} ))

script_of_the_day=${scripts[$i]}

cat $script_of_the_day
