#!/bin/bash

# Mapfile
mapfile array < hosts

# Entries in array
echo entries ${#array[*]}

# This prints every word
for line in ${array[*]}; do
	echo $line
done

IFS=$'\n'
# This prints every _line_
for line in ${array[*]}; do
	echo $line
done
unset IFS

# Or without the IFS
for (( i = 0; i < ${#array[*]}; ++i )); do
	echo ${array[i]}
done

# Delimit on dot
# http://mywiki.wooledge.org/BashGuide/Arrays
IFS=. read -a ip_elements <<< "127.0.0.1"
echo ${ip_elements[*]}
