#!/bin/bash

# The test string
readonly test='234abc234_ h___*&^    ello_élève ʘ‿ʘ'

# Array of all character classes
posix_character_classes=(
alpha	# alphabetic
alnum	# alphanumeric
ascii	# ascii
blank	# space and tab
space	# all whitespace
cntrl	# control characters
digits	# digits
xdigit	# hexadecimal digits
graph	# anything except spaces and control characters
lower	# lowercase
upper	# uppdercase
print	# visible characters
punct	# punctuation and symbols
word	# letters, numbers and underscores
)

# Loop through array of classes
for class in ${posix_character_classes[*]}; do

	# Print the class name
	echo -en $class\\t

	# Print the regular expression match
	[[ $test =~ [[:$class:]]+ ]] && echo \"$BASH_REMATCH\" || echo no match
done
