#!/bin/bash

##########
### MAC

mac="Cell 01 - Address: 90:21:06:10:5F:69 etc"

# Quick and dirty - will match valid MACs and other things
[[ $mac =~ [[:xdigit:]:]{17} ]] && echo imac $BASH_REMATCH || echo no match

##########
### IP

ip="This IP 192.168.109.10 is good"

# Quick and dirty - will match valid IPs and other things
[[ $ip =~ [0-9\.]{7,} ]] && echo quick and dirty $BASH_REMATCH || echo no match

# Long winded
[[ $ip =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]] && echo long winded $BASH_REMATCH || echo no match

# Using grouping
[[ $ip =~ ([0-9]{1,3}\.){3}[0-9]{1,3} ]] && echo using grouping $BASH_REMATCH || echo no match
